title: "IeDEA Data Tools"
description: "Scripts for data management and harmonization using the IeDEA Data Exchange Standard"
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
